version: "3.2"

services:
  lbrynet:
    image: lbry/lbrynet-tv:0.80.0
    ports:
      - "5581:5279"
      - "5279:5279"
    volumes:
      - storage:/storage
    environment:
      SDK_CONFIG: /daemon/daemon_settings.yml
      # SDK_LBRYUM_SERVERS: wallet:50001
      # SDK_LBRYUM_SERVERS: 54.226.124.145:50001
    labels:
      com.centurylinklabs.watchtower.enable: true
  app:
    image: lbry/lbrytv:latest-dev
    ports:
      - 8080:8080
    volumes:
      - storage:/storage
    environment:
      LW_LBRYNET: http://lbrynet:5279/
      LW_DEBUG: 1
    depends_on:
      - lbrynet
      - postgres
    labels:
      com.centurylinklabs.watchtower.enable: true
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/pgdata
    environment:
      POSTGRES_USER: lbrytv
      POSTGRES_PASSWORD: lbrytv
      PGDATA: /pgdata
      TZ: "UTC"
      PGTZ: "UTC"
  postgres-collector:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    volumes:
      - pgdata-collector:/pgdata
    environment:
      POSTGRES_USER: collector
      POSTGRES_PASSWORD: ZnPfJ!4vTb-nURv8M!JkkuAcjYLYbkiX
      PGDATA: /pgdata
      TZ: "UTC"
      PGTZ: "UTC"
  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --cleanup --label-enable --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9080:9090
    volumes:
      - ${PWD}/deployments/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/deployments/docker/prometheus/rules.yml:/etc/prometheus/rules.yml
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/deployments/docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  smtp:
    image: namshi/smtp:latest

volumes:
  pgdata: {}
  pgdata-collector: {}
  storage: {}
  test_storage: {}
