version: '3.2'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: lbrytv
     POSTGRES_PASSWORD: lbrytv
  lbrynet:
    image: lbry/lbrynet-tv:latest
    ports:
      - "5581:5279"
    volumes:
    - type: bind
      source: storage
      target: /storage
    environment:
      SDK_CONFIG: /daemon/daemon_settings.yml
      # SDK_LBRYUM_SERVERS: wallet:50001
      # SDK_LBRYUM_SERVERS: 54.226.124.145:50001
      SDK_LBRYUM_SERVERS: spv1.lbry.com:50001
  wallet:
    # image: lbry/wallet-server:master
    image: lbry/wallet-server:lbrytv-latest
    # command: lbry.wallet.server.coin.LBC
    ports:
      - "50001:50001"
    volumes:
    - type: bind
      source: wallet
      target: /wallet
    environment:
      # DAEMON_URL: http://lbry:lbry@127.0.0.1:9245
      TCP_PORT: 50001
      HOST: 0.0.0.0
      DAEMON_URL: http://lbry:lbry@lbrycrd:9245
      DB_DIRECTORY: /wallet
      MAX_SUBS: 1000000000000
      BANDWIDTH_LIMIT: 80000000000
      SESSION_TIMEOUT: 10000000000000000000000000
    depends_on:
      - lbrycrd
  lbrycrd:
    image: lbry/lbrycrd:linux-x86_64-production
    volumes:
    - type: bind
      source: lbrycrd
      target: /data
    environment:
      RPC_USER: lbry
      RPC_PASSWORD: lbry
      RUN_MODE: default # Available options are testnet, regtest, chainquery, default, and reindex
      RPC_ALLOW_IP: 0.0.0.0/0
      TCP_PORT: 50001
  watchtower:
    image: v2tec/watchtower
    command: --interval 30 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: lbry/lbrytv:latest-dev
    ports:
      - 8080:8080
    volumes:
    - type: bind
      source: storage
      target: /storage
    environment:
      LW_LBRYNET: http://lbrynet:5279/
    depends_on:
      - lbrynet
      - postgres
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/deployments/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/deployments/docker/prometheus/rules.yml:/etc/prometheus/rules.yml
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/deployments/docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  smtp:
    image: namshi/smtp:latest


volumes:
  storage:
  test_storage:
  wallet:
  lbrycrd:
