version: '3.2'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: lbrytv
     POSTGRES_PASSWORD: lbrytv
  lbrynet37:
    image: lbryweb/lbrynet:0.37.3
    ports:
      - "5579:5279"
    volumes:
    - type: bind
      source: storage
      target: /storage
    environment:
      LBRY_DOCKER_CONFIG: /daemon/daemon_settings.yml
  lbrynet:
    image: lbryweb/lbrynet:0.38.0
    ports:
      - "5581:5279"
    volumes:
    - type: bind
      source: storage
      target: /storage
    environment:
      SDK_CONFIG: /daemon/daemon_settings.yml
      SDK_LBRYUM_SERVERS: wallet:50001
      # SDK_LBRYUM_SERVERS: 54.226.124.145:50001
    depends_on:
      - wallet
  wallet:
    image: lbry/lbrytv-wallet:latest
    command: lbrynet.wallet.server.coin.LBC
    volumes:
    - type: bind
      source: wallet
      target: /wallet
    environment:
      # DAEMON_URL: http://lbry:lbry@127.0.0.1:9245
      DAEMON_URL: http://lbry:lbry@lbrycrd:9245
      DB_DIRECTORY: /wallet
    depends_on:
      - lbrycrd
  lbrycrd:
    image: lbry/lbrycrd:linux-x86_64-production
    environment:
      RPC_USER: lbry
      RPC_PASSWORD: lbry
      RUN_MODE: default # Available options are testnet, regtest, chainquery, default, and reindex
      RPC_ALLOW_IP: 0.0.0.0/0
  watchtower:
    image: v2tec/watchtower
    command: --interval 30 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: lbry/lbrytv:latest-dev
    ports:
      - "8080:8080"
    volumes:
    - type: bind
      source: storage
      target: /storage
    - type: bind
    environment:
      LW_LBRYNET: http://lbrynet:5279/
    depends_on:
      - lbrynet

volumes:
  storage:
  test_storage:
  wallet:
