version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: lbryweb/lbrynet:latest-rc
      - image: postgres:11-alpine
        environment:
          POSTGRES_DB: lbrytv
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  snapshot:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: GOARCH=amd64 GOOS=linux go build -o dist/linux_amd64/lbrytv main.go
      - run:
          name: Build Docker image
          command: make image
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make image
  publish-image:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get ./...
      - run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -o dist/linux_amd64/lbrytv .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make image
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image

workflows:
  version: 2
  deploy-snapshot:
    jobs:
      - test
      - publish-image:
          requires:
            - test
          filters:
            branches:
              only: master
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - publish-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - release
