version: 2
jobs:
  test:
    docker:
      - image: lbry/lbrytv-ci:latest
      - image: lbry/lbrynet-tv:latest
        environment:
          SDK_LBRYUM_SERVERS: spv1.lbry.com:50001
      - image: postgres:11-alpine
        environment:
          POSTGRES_USER: lbrytv
          POSTGRES_PASSWORD: lbrytv
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  snapshot:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make snapshot
      - run:
          name: Build Docker image
          command: make image
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make snapshot
      - run:
          name: Build Docker image
          command: make image
  publish-image:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: curl -sLO https://git.io/goreleaser && chmod +x goreleaser
      - run: go get -u github.com/gobuffalo/packr/v2/packr2
      - run: ./goreleaser --rm-dist --snapshot
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make image
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image

workflows:
  version: 2
  deploy-snapshot:
    jobs:
      - test
      - publish-image:
          requires:
            - test
          filters:
            branches:
              only: master
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - publish-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - release
