version: '3.2'

services:
  app:
    image: lbry/lbrytv:latest
    ports:
      - "8080:8080"
    volumes:
    - type: bind
      source: storage
      target: /storage
    environment:
      LW_LBRYNET: http://lbrynet:5279/
      LW_ACCOUNTSENABLED: 1
    depends_on:
      - lbrynet
      - postgres
    logging:
      driver: awslogs
      options:
        awslogs-group: lbrytv
        awslogs-region: us-east-1
        awslogs-stream: app
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
  lbrynet:
    image: lbry/lbrynet-tv:latest
    ports:
      - "5579:5279"
    volumes:
    - type: bind
      source: storage
      target: /storage
    logging:
      driver: awslogs
      options:
        awslogs-group: lbrytv
        awslogs-region: us-east-1
        awslogs-stream: lbrynet
    labels:
      com.centurylinklabs.watchtower.enable: true
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: pgdata
      target: /pgdata
    environment:
     POSTGRES_USER: lbrytv
     POSTGRES_PASSWORD: lbrytv
     PGDATA: /pgdata
  watchtower:
    image: containrrr/watchtower
    command: --interval 60 --cleanup --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/deployments/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/deployments/docker/prometheus/rules.yml:/etc/prometheus/rules.yml
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/deployments/docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  pgdata:
  storage:
  test_storage:
