BaseContentURL: https://api.lbry.tv/content/
InternalAPIHost: https://api.lbry.com

SentryDSN: "https://9ef75ef77a844d4aa35d834d78266477@sentry.io/1416147"

DatabaseConnection: postgres://lbrytv:lbrytv@postgres
DatabaseName: lbrytv
DatabaseOptions: sslmode=disable

IsAccountV1Enabled: 0
