BaseContentURL: https://api.lbry.tv/content/
InternalAPIHost: https://api.lbry.com

SentryDSN: "https://9ef75ef77a844d4aa35d834d78266477@sentry.io/1416147"

Database:
  Connection: postgres://lbrytv:lbrytv@postgres
  DBName: lbrytv
  Options: sslmode=disable

AccountsEnabled: 0

MetricsAddress: :2112
MetricsPath: /metrics
